apiVersion: v1
kind: Service
metadata:
  name: protein-classification-service
  labels:
    app: protein-classification-service
spec:
  selector:
    app: protein-classification-service
  ports:
    - name: rest
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protein-classification-deployment
  labels:
    app: protein-classification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protein-classification-service
  template:
    metadata:
      labels:
        app: protein-classification-service
    spec:
      containers:
        - name: prot-svc
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: CONFIG_MAP
              value: config-map/{{ .Values.serviceDependencies.configName }}.yml
            - name: LOGIT_MAP
              value: logit-map/{{ .Values.serviceDependencies.logitName }}.json
            - name: TOKEN_MAP
              value: token-map/{{ .Values.serviceDependencies.tokenName }}.json
            - name: MODEL_WEIGHTS
              value: {{ .Values.serviceDependencies.modelDir }}/{{ .Values.modelWeights.name }}.bin
          volumeMounts:
            - mountPath: /{{ .Values.serviceDependencies.modelDir }}
              name: model-weights
      initContainers:
        - name: pull-model-weights
          image: google/cloud-sdk:380.0.0-slim
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              echo pulling model weights

              gsutil cp $MODEL_WEIGHTS .
              tar -xvf `basename $MODEL_WEIGHTS` -C $MODEL_WEIGHTS_DIR

              echo weights pulled
          env:
            - name: MODEL_WEIGHTS
              value: {{ .Values.modelWeights.registry }}{{ .Values.modelWeights.name }}.tar.gz
            - name: MODEL_WEIGHTS_DIR
              value: {{ .Values.serviceDependencies.modelDir }}
          volumeMounts:
            - mountPath: /{{ .Values.serviceDependencies.modelDir }}
              name: model-weights
      volumes:
        - name: model-weights
          hostPath:
            path: /{{ .Values.serviceDependencies.modelDir }}
