---
model:
  name: ConvolutionClassifier
  param:
    num_embeddings: 25
    embedding_dim: 64
    n_residual_blocks: 4
    residual_block_def:
      block_channels: 128
      kernel_size: 3
      dilation: 2
      padding: same
    num_labels: 10_000
    pooling: amax
env:
  batch_size: 1024
  epochs: 80
optim:
  lr: 1e-2
  weight_decay: 0.01
lr_scheduler:
  base_lr: 5e-5
  max_lr: 1.5e-4
  cycle_momentum: false
