---
model:
  name: MLP
  param:
    d_model: 10
    seq_len: 512
    hidden_dim: 20000
    negative_slope: 0.3
    num_labels: 15259
    dropout: 0.01
env:
  batch_size: 128
  epochs: 4
optim:
  lr: 1e-5
  weight_decay: 0.01
