---
model:
  name: MLPOneHot
  param:
    n_tokens: 26
    seq_len: 512
    embed_dim: 256
    negative_slope: 0.3
    num_labels: 1000
    dropout: 0.01
env:
  batch_size: 128
  epochs: 30
optim:
  lr: 1e-5
  weight_decay: 0.01
