---
model:
  name: TransformerClassifier
  param:
    n_tokens: 25
    d_model: 64
    seq_len: 256
    n_head: 8
    dim_ff: 512
    n_layers: 5
    hidden_dim: 1024
    negative_slope: 0.3
    num_labels: 10_000
    dropout: 0.1
env:
  batch_size: 512
  epochs: 8
optim:
  lr: 4e-5
  weight_decay: 0.01
