image:
  registry: docker.io/btenmann
  name: protein-classification-service
  tag: 1.5.0
modelWeights:
  registry: gs://protein-classification-service/
  name: model.flx
serviceDependencies:
  configName: resnet
  logitName: logit_map
  tokenName: token_map
  modelDir: weights
